=for comment $Id: Packages.pod,v 1.2 2006/07/16 11:09:33 robertemay Exp $

=head1 NAME

Win32::GUI::Reference::Packages - Core packages

=head1 DESCRIPTION

This page provides a summary of the packages available with Win32::GUI.

=head1 PACKAGES

=over

__W32G_PACKLIST__

=back

__W32G_POSTAMBLE__
